# -*- coding: utf-8 -*-
"""AnaliseDeDados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qaGDWMZ9D0CGa-T7sJ8kB-rwlurEOu3l
"""

import pandas as pd ### importando o pandas
url = 'https://github.com/erbson/datascience/blob/master/Produtos.xls?raw=true' ### url do arquivo de dados
dados = pd.read_excel(url) ###  lendo o arquivo remoto
dados ### dando um print no arquivo
dados['tipo'].unique() ### Analisando a coluna especifica.
dados['tipo'] ### vendo o conteudo
dados['Produto'].value_counts() ### obtendo a quantidade de produtos

dados['tipo'].value_counts().plot.pie() ### gerando um grafico de pizza.

dados['tipo'].value_counts().plot.bar() ### gerando um grafico de barras